DAQlml: DAQtest Class Reference
DAQtest Class Reference
test device
#include <DAQtest.h>
Public Member Functions
int test_print_instruction (int sw)
Print instructions depending of the type of signal we want to test (sinus,square...).
int load_parameter (const std::string file_name)
template<typename T >
int detect_edges (cimg_library::CImg< float > data, cimg_library::CImg< int > &raisingedges, cimg_library::CImg< int > &fallingedges, T threshold, int verbose, bool borders)
detect edges from sqwave single channel data
template<typename T >
int duration_samples (cimg_library::CImg< T > raisingedges, cimg_library::CImg< T > fallingedges, cimg_library::CImg< T > &duration_up, CImg< T > &duration_down)
template<typename Tin , typename Tout >
int duration_sampletotime (cimg_library::CImg< Tin > duration_up, int frequence_acqui, cimg_library::CImg< Tout > &duration_up_time)
template<typename T >
int period (cimg_library::CImg< T > uporDC, cimg_library::CImg< T > duration_down_time, cimg_library::CImg< T > &TorF)
template<typename T >
int compute_duty_cycle (cimg_library::CImg< T > &uporDC, cimg_library::CImg< T > &period)
calculation of duty cycle
template<typename T >
int compute_frequence_cycle (cimg_library::CImg< T > DC, cimg_library::CImg< T > &TorF)
calculation of frequence
template<typename T >
int compute_filter_data (cimg_library::CImg< T > data, cimg_library::CImg< T > &data_filter)
data filter
template<typename T >
int compute_filter_error (cimg_library::CImg< T > &duration_up, cimg_library::CImg< T > &raisingedges, cimg_library::CImg< T > &data_error_filter)
detect error
template<typename T >
int compute_data_histogram (cimg_library::CImg< T > data, T frequence_acqui, cimg_library::CImg< T > &data_histogram)
data histogram
template<typename T >
int test_signal (cimg_library::CImg< T > data, int frequence_acqui, bool filter, bool DCfreq, int display, T reference_frequency, T reference_DC, T reference_tolerance)
test for TTL (i.e. square signal)
Public Attributes
float reference_frequency
float reference_DC
float reference_tolerance
bool DCfrequency
bool gaussian_filter
Detailed Description
test device
test of characteristics of a square wave : period, DC...
Definition at line 13 of file DAQtest.h.
Member Function Documentation
template<typename T > int DAQtest::compute_data_histogram (cimg_library::CImg< T > data, T frequence_acqui, cimg_library::CImg< T > & data_histogram) [inline]
data histogram
This fonction class the data in a histogram
Parameters:
[in] data all values ...
[in] frequence_acqui
[out] data_histogram
Definition at line 337 of file DAQtest.h.
References PR.
Referenced by test_signal().
template<typename T > int DAQtest::compute_duty_cycle (cimg_library::CImg< T > & uporDC, cimg_library::CImg< T > & period) [inline]
calculation of duty cycle
This fonction return the duty cycle
Parameters:
[in] uporDC=duration up in time
[in] period
[out] uporDC= Duty cycle
Definition at line 219 of file DAQtest.h.
References period().
Referenced by test_signal().
template<typename T > int DAQtest::compute_filter_data (cimg_library::CImg< T > data, cimg_library::CImg< T > & data_filter) [inline]
data filter
this fonction delete the outlier data
Parameters:
[in] data all values...
[out] data filter
Definition at line 251 of file DAQtest.h.
Referenced by test_signal().
template<typename T > int DAQtest::compute_filter_error (cimg_library::CImg< T > & duration_up, cimg_library::CImg< T > & raisingedges, cimg_library::CImg< T > & data_error_filter) [inline]
detect error
this fonction detect the error data after the filter
Parameters:
[in] data all values...
[out] data error
Definition at line 305 of file DAQtest.h.
Referenced by test_signal().
template<typename T > int DAQtest::compute_frequence_cycle (cimg_library::CImg< T > DC, cimg_library::CImg< T > & TorF) [inline]
calculation of frequence
This fonction return the frequence
Parameters:
[in] TorF= period
[out] TorF=frequence cycle
Definition at line 235 of file DAQtest.h.
Referenced by test_signal().
template<typename T > int DAQtest::detect_edges (cimg_library::CImg< float > data, cimg_library::CImg< int > & raisingedges, cimg_library::CImg< int > & fallingedges, T threshold, int verbose, bool borders) [inline]
detect edges from sqwave single channel data
detect edges from sqwave single channel data this function returns raising edge separation, falling edge separation and duration
Parameters:
[in] data
[out] raisingedges
[out] fallingedges
[in] threshold
verbose
[in] borders
Returns:
Definition at line 95 of file DAQtest.h.
Referenced by test_signal().
template<typename T > int DAQtest::duration_samples (cimg_library::CImg< T > raisingedges, cimg_library::CImg< T > fallingedges, cimg_library::CImg< T > & duration_up, CImg< T > & duration_down) [inline]
Definition at line 161 of file DAQtest.h.
Referenced by test_signal().
template<typename Tin , typename Tout > int DAQtest::duration_sampletotime (cimg_library::CImg< Tin > duration_up, int frequence_acqui, cimg_library::CImg< Tout > & duration_up_time) [inline]
This fonction return the data conversion between samples to unity of time
Parameters:
[in] data in samples
[out] data in unity of time
Definition at line 182 of file DAQtest.h.
Referenced by test_signal().
int DAQtest::load_parameter (const std::string file_name) [inline]
open file from its name
open test variable (i.e. process variable)
Bug:
process should be int or byte instead of float
load attributes (i.e. process parameters)
Todo:
[low] add error messages for all attributes
Definition at line 43 of file DAQtest.h.
References DCfrequency, gaussian_filter, reference_DC, reference_frequency, and reference_tolerance.
Referenced by main().
template<typename T > int DAQtest::period (cimg_library::CImg< T > uporDC, cimg_library::CImg< T > duration_down_time, cimg_library::CImg< T > & TorF) [inline]
This fonction return the period data
Parameters:
[in] uporDC = duration up in unity of time
[in] duration_down_time
[out] TorF = period
Definition at line 200 of file DAQtest.h.
Referenced by compute_duty_cycle(), and test_signal().
int DAQtest::test_print_instruction (int sw) [inline]
Print instructions depending of the type of signal we want to test (sinus,square...).
detect edges from sqwave single channel data this function returns raising edge separation, falling edge separation and duration
Parameters:
[in] data
Definition at line 30 of file DAQtest.h.
References TEST_SQWAVE.
Referenced by main().
template<typename T > int DAQtest::test_signal (cimg_library::CImg< T > data, int frequence_acqui, bool filter, bool DCfreq, int display, T reference_frequency, T reference_DC, T reference_tolerance) [inline]
test for TTL (i.e. square signal)
Parameters:
[in] reference_duration_up,: duration of the TTL (i.e. upper level lenght in second)
[in] reference_frequency,: frequency of the TTL (i.e. inverse of total period in second)
Todo:
check scaling histogram for up or DC
Todo:
. scale histogram for T or F
Definition at line 370 of file DAQtest.h.
References compute_data_histogram(), compute_duty_cycle(), compute_filter_data(), compute_filter_error(), compute_frequence_cycle(), detect_edges(), duration_samples(), duration_sampletotime(), and period().
Referenced by main().
Member Data Documentation
bool DAQtest::DCfrequency
Definition at line 20 of file DAQtest.h.
Referenced by load_parameter(), and main().
bool DAQtest::gaussian_filter
Definition at line 21 of file DAQtest.h.
Referenced by load_parameter(), and main().
float DAQtest::reference_DC
Definition at line 18 of file DAQtest.h.
Referenced by load_parameter(), and main().
float DAQtest::reference_frequency
Definition at line 17 of file DAQtest.h.
Referenced by load_parameter(), and main().
float DAQtest::reference_tolerance
Definition at line 19 of file DAQtest.h.
Referenced by load_parameter(), and main().
The documentation for this class was generated from the following file:
DAQtest.h