DAQlml: DAQcomedi.h File Reference
DAQcomedi.h File Reference
Classes
class DAQdevice
acquisition device
Functions
int print_help (std::ostream &stream)
display help options
template<typename Tacquisition , typename Tphysical >
int convert_to_phys (cimg_library::CImgList< Tacquisition > &data, cimg_library::CImgList< Tphysical > &data_phys, DAQdevice DAQdev)
convert integer 16bit binary data into float physical voltage
template<typename Tacquisition , typename Tphysical >
int convert_from_phys (cimg_library::CImgList< Tphysical > &data_phys, cimg_library::CImgList< Tacquisition > &data, DAQdevice DAQdev, const bool assign=true)
convert float physical voltage into integer 16bit binary data
template<typename Tdata , typename Ttime >
int create_time (cimg_library::CImgList< Tdata > &data, cimg_library::CImgList< Ttime > &time, DAQdevice DAQdev)
create time corresponding to each sample
char * cmd_src (int src, char *buf)
subfunction of
char * tobinary (char *s, int bits, int n)
void probe_max_1chan (comedi_t *it, int s)
void get_command_stuff (comedi_t *it, int s)
int get_board_info (std::string fd, bool verbose)
Function Documentation
char* cmd_src (int src, char * buf)
subfunction of
Definition at line 412 of file DAQcomedi.h.
Referenced by get_command_stuff(), and probe_max_1chan().
template<typename Tacquisition , typename Tphysical > int convert_from_phys (cimg_library::CImgList< Tphysical > & data_phys, cimg_library::CImgList< Tacquisition > & data, DAQdevice DAQdev, const bool assign = true) [inline]
convert float physical voltage into integer 16bit binary data
Parameters:
data integer binary
data_phys physical voltage
[inout] DAQdev DAQdevice object
Returns:
Definition at line 360 of file DAQcomedi.h.
References DAQdevice::comedirange, and DAQdevice::maxdata.
template<typename Tacquisition , typename Tphysical > int convert_to_phys (cimg_library::CImgList< Tacquisition > & data, cimg_library::CImgList< Tphysical > & data_phys, DAQdevice DAQdev) [inline]
convert integer 16bit binary data into float physical voltage
Parameters:
[in] data integer binary
[inout] data_phys physical voltage
[in] DAQdev DAQdevice object
Returns:
Definition at line 337 of file DAQcomedi.h.
References DAQdevice::comedirange, and DAQdevice::maxdata.
Referenced by main().
template<typename Tdata , typename Ttime > int create_time (cimg_library::CImgList< Tdata > & data, cimg_library::CImgList< Ttime > & time, DAQdevice DAQdev) [inline]
create time corresponding to each sample
create time corresponding to each sample the delay between channels is also taken into account
Parameters:
[in] data
[out] time
[in,out] DAQdev
sampling_rate
Returns:
Definition at line 386 of file DAQcomedi.h.
References DAQdevice::cmd, and DAQdevice::sampling_rate.
Referenced by main().
int get_board_info (std::string fd, bool verbose)
Definition at line 487 of file DAQcomedi.h.
References get_command_stuff().
Referenced by main().
void get_command_stuff (comedi_t * it, int s)
Definition at line 469 of file DAQcomedi.h.
References cmd_src(), and probe_max_1chan().
Referenced by get_board_info().
int print_help (std::ostream & stream)
display help options
   print_help(std::cout);
Returns:
Todo:
[low] should be in DAQdevice class
Definition at line 320 of file DAQcomedi.h.
Referenced by main().
void probe_max_1chan (comedi_t * it, int s)
Definition at line 447 of file DAQcomedi.h.
References cmd_src().
Referenced by get_command_stuff().
char* tobinary (char * s, int bits, int n)
Definition at line 435 of file DAQcomedi.h.