DAQlml: DAQdata.h File Reference
DAQdata.h File Reference
Functions
template<typename T >
int load_data (std::string file_name, std::vector< std::string > var_names, std::vector< std::string > &unit_names, std::vector< std::string > &dim_names, CImgList< T > &channels)
load previously recorded data
template<typename Tdata , typename Tacqu >
int load_data_attribute (std::string file_name, std::string var_name, int &sampling_rate, Tacqu &acqu_range_min, Tacqu &acqu_range_max, std::string &acqu_range_unit, Tdata &phys_range_min, Tdata &phys_range_max, std::string &phys_range_unit)
load previously recorded data information
template<typename Tdata , typename Tacqu >
int load_data (std::string file_name, std::vector< std::string > var_names, std::vector< std::string > &unit_names, std::vector< std::string > &dim_names, CImgList< Tdata > &channels, int &sampling_rate, Tacqu &acqu_range_min, Tacqu &acqu_range_max, std::string &acqu_range_unit, Tdata &phys_range_min, Tdata &phys_range_max, std::string &phys_range_unit)
load previously recorded data
template<typename Tdata , typename Ttime , typename Tacqu >
int save_data (std::string file_name, cimg_library::CImgList< Tdata > &data, cimg_library::CImgList< Ttime > &time, DAQdevice DAQdev, std::string data_unit_name, Tacqu acqu_range_min, Tacqu acqu_range_max, std::string &acqu_range_unit, Tdata phys_range_min, Tdata phys_range_max, std::string &phys_range_unit)
save recorded data and additional informations
Function Documentation
template<typename Tdata , typename Tacqu > int load_data (std::string file_name, std::vector< std::string > var_names, std::vector< std::string > & unit_names, std::vector< std::string > & dim_names, CImgList< Tdata > & channels, int & sampling_rate, Tacqu & acqu_range_min, Tacqu & acqu_range_max, std::string & acqu_range_unit, Tdata & phys_range_min, Tdata & phys_range_max, std::string & phys_range_unit) [inline]
load previously recorded data
load previously recorded data as many channels in a list (i.e. CImgList container)
Note:
all channels should have the same size (i.e. 1D data with same width)
Parameters:
[in] file_name file name (e.g. "data.nc")
[in] var_names variable names (i.e. the requested list of channels;e.g. "pressure, hot_wire, square_wave, control_signal")
[out] unit_names variable unit names (i.e. unit names of channels; e.g. "Pa","m/s","V","volt")
[out] dim_names dimension name (i.e. only one dimension name in the list as channels are 1D data; e.g. "time")
[out] channels data as physical values (i.e. all requested channels in the data list)
[out] ...
Note:
code progress: data from CImg to CImgList . DONE
code progress: function as template. DONE
Todo:
[low] remove std::cout<<CImgListNetCDF::loadNetCDF... progress terminal output, and both return and output on error only !
[very low] separate load header and data (looking forward to NetCDF unlimited dimension)
load NetCDF data values
load NetCDF acquisition information
Definition at line 105 of file DAQdata.h.
References load_data(), and load_data_attribute().
template<typename T > int load_data (std::string file_name, std::vector< std::string > var_names, std::vector< std::string > & unit_names, std::vector< std::string > & dim_names, CImgList< T > & channels) [inline]
load previously recorded data
load previously recorded data as many channels in a list (i.e. CImgList container)
Note:
all channels should have the same size (i.e. 1D data with same width)
Parameters:
[in] file_name file name (e.g. "data.nc")
[in] var_names variable names (i.e. the requested list of channels;e.g. "pressure, hot_wire, square_wave, control_signal")
[out] unit_names variable unit names (i.e. unit names of channels; e.g. "Pa","m/s","V","volt")
[out] dim_names dimension name (i.e. only one dimension name in the list as channels are 1D data; e.g. "time")
[out] channels data as physical values (i.e. all requested channels in the data list)
check prequisite
[optional] show dimension; should be one only
open file in read only mode
load NetCDF header
load dimension (e.g. "time")
[optional] show dimension; should be one only
load NetCDF header
load NetCDF data
Definition at line 14 of file DAQdata.h.
Referenced by load_data().
template<typename Tdata , typename Tacqu > int load_data_attribute (std::string file_name, std::string var_name, int & sampling_rate, Tacqu & acqu_range_min, Tacqu & acqu_range_max, std::string & acqu_range_unit, Tdata & phys_range_min, Tdata & phys_range_max, std::string & phys_range_unit) [inline]
load previously recorded data information
load previously recorded data as many channels in a list (i.e. CImgList container)
Note:
all channels should have the same size (i.e. 1D data with same width)
Parameters:
[in] file_name file name (e.g. "data.nc")
[out] ...
open file from its name
read variable
load attributes (i.e. data information)
data attribute ranges
Todo:
. [medium] read others attributes
Definition at line 54 of file DAQdata.h.
Referenced by load_data().
template<typename Tdata , typename Ttime , typename Tacqu > int save_data (std::string file_name, cimg_library::CImgList< Tdata > & data, cimg_library::CImgList< Ttime > & time, DAQdevice DAQdev, std::string data_unit_name, Tacqu acqu_range_min, Tacqu acqu_range_max, std::string & acqu_range_unit, Tdata phys_range_min, Tdata phys_range_max, std::string & phys_range_unit) [inline]
save recorded data and additional informations
save all recoreded data regarding to a single time axis (in order to display it with time axis under ncview for example)
Note:
each recorded channel is also written with its corresponding time axis (especially with the channel name prefix)
Parameters:
fo
data
time
DAQdev
data_unit_name
Returns:
Todo:
[medium] make NetCDF file object version (save_data(NcFile*fp,...) and its overload with file name
open file (shared between fod and fot)
create dimension (shared between fod and fot)
Note:
set both dimension and axis names of time to "time"
create variables (and attributes)
data variables /data attribute units
time variables (first for all data, then each data have it own time) /time data
time units
Todo:
add unit__long_name="second" refering to unit="s"
create global attributes
sampling rate
sampling rate
Todo:
. save range: acquisition [min, max], physical [min, max] (as both global and local attribute)
write data
data
time
Definition at line 133 of file DAQdata.h.
References DAQdevice::channel_index, DAQdevice::channel_name, DAQdevice::range_id, and DAQdevice::sampling_rate.
Referenced by main().