DAQlml: test.h File Reference
test.h File Reference
Functions
template<typename T >
int detect_edges (cimg_library::CImg< T > &data, cimg_library::CImg< int > &raising_separation, cimg_library::CImg< int > &falling_separation, cimg_library::CImg< int > &duration, int threshold, int verbose)
detect edges from sqwave single channel data
int test_print_instruction (int sw)
int test_sinwave ()
test acquisition using sinwave
int test_square_wave (cimg_library::CImg< int > data, int sampling_rate)
test acquisition using sq wave
int test_square_wave (cimg_library::CImgList< int > data, int sampling_rate)
Variables
const int TEST_SQWAVE = 1
const int TEST_SINWAVE = 2
Function Documentation
template<typename T > int detect_edges (cimg_library::CImg< T > & data, cimg_library::CImg< int > & raising_separation, cimg_library::CImg< int > & falling_separation, cimg_library::CImg< int > & duration, int threshold, int verbose) [inline]
detect edges from sqwave single channel data
detect edges from sqwave single channel data this function returns raising edge separation, falling edge separation and duration
Parameters:
data
raising_separation
falling_separation
duration
threshold
verbose
Returns:
Todo:
for all channels
Definition at line 21 of file test.h.
Referenced by test_square_wave().
int test_print_instruction (int sw)
Definition at line 102 of file test.h.
References TEST_SQWAVE.
int test_sinwave ()
test acquisition using sinwave
NOT IMPREMENTED YET test acquisition using sinwave to check the delay between the signals
Returns:
Definition at line 120 of file test.h.
int test_square_wave (cimg_library::CImgList< int > data, int sampling_rate)
Todo:
put the number of channel to use for the square wave test in the .cdl file
Definition at line 174 of file test.h.
References test_square_wave().
int test_square_wave (cimg_library::CImg< int > data, int sampling_rate)
test acquisition using sq wave
Parameters:
data
sampling_rate
Returns:
Definition at line 131 of file test.h.
References detect_edges().
Referenced by test_square_wave().
Variable Documentation
const int TEST_SINWAVE = 2
Definition at line 5 of file test.h.
const int TEST_SQWAVE = 1
Definition at line 4 of file test.h.